name: Continuous Delivery

on: 
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    uses: levigo/reusable-workflows/.github/workflows/continuous-delivery-np.yml@8e3ab49979d3a502210030088de5ca3016f209b4
    secrets: inherit
    with:
      mattermostChannel: 'neverpile-ci'
      jdkVersion: '11'
