name: Continuous Delivery

on: 
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    uses: levigo/reusable-workflows/.github/workflows/continuous-delivery-np.yml@feat/INF-28_license-check
    secrets: inherit
    with:
      mattermostChannel: 'neverpile-ci'
      jdkVersion: '11'
      multiModule: true
  updateReadme:
    needs: build
    uses: levigo/reusable-workflows/.github/workflows/update-readme-md.yml@v3
    secrets: inherit
    with:
      releaseVersion: ${{ needs.build.outputs.releaseVersion }}
