name: Continuous Integration

on: 
  push:
    branches-ignore:
      - master
    paths-ignore:
      - '**/README.md'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-continuous-integration:
    uses: levigo/reusable-workflows-pub/.github/workflows/continuous-integration.yml@latest
    secrets: inherit
    with:
      notifyMattermost: false
      matrix:  '{"jdk": [21]}'
      multiModule: true
