name: Continuous Delivery

on: 
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    uses: levigo/reusable-workflows-pub/.github/workflows/continuous-delivery-np.yml@latest
    secrets: inherit
    with:
      multiModule: true
      jdkVersion: 25
  updateReadme:
    needs: build
    uses: levigo/reusable-workflows-pub/.github/workflows/update-readme-md.yml@latest
    secrets: inherit
    with:
      releaseVersion: ${{ needs.build.outputs.releaseVersion }}
