name: Continuous Integration

on: 
  push:
    branches-ignore:
      - master
    paths-ignore:
      - '**/README.md'

jobs:
  call-continuous-integration:
    uses: levigo/reusable-workflows-pub/.github/workflows/continuous-integration.yml@latest
    secrets: inherit
    with:
      notifyMattermost: false
      matrix:  '{"jdk": [17]}'
      multiModule: true
